# vim:ft=yaml.ansible:ts=2:sw=0:et
---
- name: install and configure Jackett
  tags:
    - media
    - web
  block:
    - name: create config directory
      ansible.builtin.file:
        state: directory
        path: /dockers/media

    - name: copy docker-compose file
      ansible.builtin.template:
        src: plex/jackett.docker-compose.yml
        dest: /dockers/media/docker-compose.yml

    - name: start containers
      ansible.builtin.docker_compose:
        project_src: /dockers/media
        state: present

    - name: configure nginx proxy for media server
      ansible.builtin.template:
        src: plex/nginx.conf
        dest: /etc/nginx/sites-available/media.conf

    - name: enable nginx proxy for media server
      ansible.builtin.file:
        src: /etc/nginx/sites-available/media.conf
        dest: /etc/nginx/sites-enabled/media.conf
        state: link

    - name: restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
