# vim:ft=yaml.ansible:ts=2:sw=0:et
---
- name: Install nginx
  tags: web
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: latest

- name: Configure nginx server
  tags: web
  ansible.builtin.template:
    src: nginx/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy common config
  tags: web
  ansible.builtin.template:
    src: nginx/common.conf
    dest: /etc/nginx/common.conf

- name: copy common location config
  tags: web
  ansible.builtin.template:
    src: nginx/common_location.conf
    dest: /etc/nginx/common_location.conf

- name: copy SSL-related config
  tags:
    - web
    - security
  ansible.builtin.template:
    src: nginx/ssl.conf
    dest: /etc/nginx/ssl.conf

- name: Start and enable service
  tags: web
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
