# vim:ft=yaml.ansible:ts=2:sw=0:et
---
- name: Get `get-docker.sh` script
  tags: docker
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh

- name: Install docker
  tags: docker
  ansible.builtin.shell:
    creates: /bin/docker
    cmd: sh /tmp/get-docker.sh && rm -f /tmp/get-docker.sh

- name: Append `docker` group to remote user
  tags:
    - docker
    - user
  ansible.builtin.user:
    name: "{{ username }}"
    append: true
    groups: docker

- name: Enable docker service
  tags: docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install docker-compose
  tags: docker
  ansible.builtin.pip:
    name: docker-compose
    state: latest
    extra_args: "--break-system-packages"
