# vim:ft=yaml.ansible:ts=2:sw=0:et
---
- name: Update sshd config
  tags:
    - base
    - ssh
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: Restart sshd service
  tags:
    - base
    - ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
